### ISSUE TITLE
Collection vs Composition

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/core-ig#39]
Should the Phenopacket be modeled as a Composition (file:///home/peter/GIT/core-ig/output/StructureDefinition-Phenopacket.html) or as a Collection?
Thoughts?

**Comment by khalifa-aly** [comment]
According to my understanding, it may better to be represented as a FHIR Composition than a FHIR Bundle. Compositions may represent the relation between included resources.
More details may be  found in the following links:
-	https://www.hl7.org/fhir/bundle.html#bnr
- 	https://www.hl7.org/fhir/composition.html

**Comment by pnrobinson** [comment]
One issue for Composition is that we need to indicate a type (Codeable concept), which is recommended to be a LOINC term. If we decide to stick with Composition, then we should ask LOINC to add Phenopacket as a document type. For now I am using
```
$LOINC#LOINC_11516-2 "Physician Episode of care medical records"
```
in an example.

**Comment by khalifa-aly** [comment]
It would be great if we can get LOINC code for the composition and may be for other building blocks as well. However, this is a preferred not mandatory binding to LOINC or FHIR doc type value set. According to FHIR "[Preferred](https://www.hl7.org/fhir/terminologies.html#preferred)" terminology or value set binding is:
"Instances are encouraged to draw from the specified codes for interoperability purposes but are not required to do so to be considered conformant.".
We may think of developing our value set for describing various building blocks and then we may purpose them to LOINC in order to get a code?

**Comment by pnrobinson** [comment]
We are sticking with Composition.
